
project_id = "nljlsqgldgmxlbylqazg"

[functions.imagen-generator]
verify_jwt = false

[functions.drive-ai-assistant]
verify_jwt = false

[functions.slack-data]
verify_jwt = false

[functions.unified-agent]
verify_jwt = false
