// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nljlsqgldgmxlbylqazg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5samxzcWdsZGdteGxieWxxYXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Mjc3NjMsImV4cCI6MjA2MTAwMzc2M30.tLiL3le_jejY1JvDnwcr6a_1T6W_TjTserEbPJq2svw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);